---
title: "Notes_pipeline"
author: "Cindy P."
format: html
editor: visual
---

## Pre-steps

Download [git](https://git-scm.com/downloads), R+RStudio (<https://posit.co/download/rstudio-desktop/>)

Create a [Github](https://github.com/) account\* remember the email/username + SSH key (please, follow the steps from Generating a new SSH key & Testing your SSH connection).

In R install the library "usethis"

## Glossary

They're really technical words, but they're necessary to better understand the Github terms. I simplify the concept so is easier to follow this workshop.

**Pull request:** when we're collaborating and we have made changes so, we already review them, we'll update the document by merging the "old" version with the reviewed one trough this process.

**Push:** synonym for updating the file (green ascending arrow).

**Pull:** when we download the most recent version of the file (blue descending arrow).

**Branch:** think on"divided & conquer". We have 2 types the main and secondaries. The main branch is where we create the document. While, the secondary branch is for each of the collaborators or sections, each of these branches after pushing and accepting the pull request will be included in the main branch.

**Repository:** the equivalent of an R-project.

**Commit:** the notes that we made for a milestone during changes in the document, could be major or minor edits (documents with a check).

Fun fact, the difference between Git and Github, as is indicated in the name Github is a hub of gits (and other stuff). The formal definitions are:

**GitHub** is a *cloud-based* platform that hosts Git repositories. It is a web service built on top of Git.

**Git** is a free, open-source distributed version control system (DVCS). It is a *software* tool installed locally on a developer's machine.

NOTE: as we have Git in R, we will have that new tab on the environments panel. Here we will see the bottoms that I described in the parenthesis.

## First steps

Before starting we should verify everything is runing well and prepare our set-up, for that we should have:

-   Git installed and synchronized with our Github account (SSH key with a successful connection).

-   library(usethis) use_git_config(user.name = "your.user.name", user.email = "same.as.gitub")

**Hands-on:**

1.  Create a repository for working (as is the first time we might use a Token from Github\*)
2.  Create a new R project\> control version\> Git\> copy our link from Github
    1.  If it auto-completes means we're all good! If not we need to double check the token or the SSH key.
3.  Voila! We're ready to work :)

## The theory

To commit: we need to check the documents/files we're interested to upload (save them). So from ? will pass to A (selected), write my note in Commit, immediately after Push.

-   If we modified something a "M" will appear, when we're ready to push again repeat the process: save changes, commit, push. In case I was working with another version from another branch first I need to Pull, modify, save changes, commit and push.

    **NOTE: The order matters! So, remembered that tip ;)**

Creating secondary branches so we can collaborate, made our own modifications, review them and do a pull-request! (the main goal of this workshop). When I learnt it, I found it pretty confusing but necessary (& helpful) for doing Science. How to do it? (Step by step)

1.  On the Git section, we will see where we're located. In this case should be "main", as we haven't create other branches yet. If we click on the arrow, a menu will be displayed with the branches we've created.

2.  Right now, it's empty, so let's go to Github, in our repository (i.e., github_cindys_notes), just belowe the name on the left we will see main bottom.

3.  If we click on it and type the name of our branch we'll create a new one, also here is where we can modify the branches. This

## The excersice:

The best way to learn is trough practice, that means we will made lots of mistakes but that's the best way to learn, because you'll remember the struggle and the solutions.
